### ISSUE TITLE
GLBs load with images, but GLTF files can't load images

### ISSUE THREAD

**Issue by fire** [AllenDang/model_explorer_godot4#1]
Tested build.

https://github.com/V-Sekai-fire/VSK_model_explorer

https://cdn.discordapp.com/attachments/714269155523690587/1045043164517498910/game_windows.zip

![image](https://user-images.githubusercontent.com/32321/203621760-11822f2c-dca9-4c51-9c99-903c0eb039f8.png)

[untitled.glb.zip](https://github.com/AllenDang/model_explorer_godot4/files/10078226/untitled.glb.zip)

![image](https://user-images.githubusercontent.com/32321/203621996-990aff20-636c-40ba-b76e-6832fcd171a7.png)

[donut_3_0.zip](https://github.com/AllenDang/model_explorer_godot4/files/10078232/donut_3_0.zip)

**Comment by AllenDang** [comment]
I guess it should be bug for GLTFDocument...

**Comment by fire** [comment]
Looking into this.

**Comment by fire** [comment]
Added https://github.com/godotengine/godot/pull/69181.

**Comment by fire** [comment]
Discussed with the project manager how the above pr is a hacky way that can work but isn't well designed as we've had problems designing a good runtime file import api.

**Comment by fire** [comment]
@AllenDang Please check this is fixed.

**Comment by AllenDang** [comment]
@fire Wow! Thanks to inform me. I'll test it and feedback to you later.

**Comment by fire** [comment]
As far as I know this is fixed in 4.0 stable.
