### ISSUE TITLE
Add vertex count and count faces

### ISSUE THREAD

**Issue by fire** [AllenDang/model_explorer_godot4#2]
![image](https://user-images.githubusercontent.com/32321/203624215-4025cd04-c006-4fd7-8fe3-0bda349b7487.png)

```gdscript
func _on_timer_timeout():
	var index_count : int = RenderingServer.viewport_get_render_info(
		get_viewport().get_viewport_rid(),
		RenderingServer.VIEWPORT_RENDER_INFO_TYPE_VISIBLE, 
		RenderingServer.VIEWPORT_RENDER_INFO_PRIMITIVES_IN_FRAME)
	print("Vertices on the screen %d" % index_count)
```

Add a TimerNode with wait time of like 5 seconds, autostart and a callback assigned to _on_timer_timeout on `res://scene/ModelExplorer.tscn`

**Comment by fire** [comment]
I wanted to create a label, but didn't want to do ui design.

**Comment by AllenDang** [comment]
@fire Thanks for the solution, it's really quick. This could get the overall vertex count in screen, may I ask is there any similar way to get vertex count for each mesh?

**Comment by fire** [comment]
I don't think I ever finished this for godot engine 4.0 and I'm not in the right context to restart work on it. You can salvage the ideas https://github.com/godotengine/godot/pull/43830

**Comment by fire** [comment]
You may be able to write a gltf document extension to count it and save it in a data structure though when importing as a work around.

**Comment by AllenDang** [comment]
@fire Sure, I'll check the extension path.

**Comment by fire** [comment]
@AllenDang what information do you need? 

Khronos says at least these ones.

-  File Size (min/max)
-  Triangle Count (max)
-  Material Count (max)
-  Texture Map Resolution Power of 2
-  Dimensions (min/max)
-  Dimensions (product within tolerance)

https://github.com/fire-3dc

**Comment by AllenDang** [comment]
@fire Triangle Count, that's new to me, thanks for pointing out, more dig now.

**Comment by AllenDang** [comment]
@fire I did a quick check, glTF-Validator could be a useful tool to provide a issue report, and it could provide total triangle count, but for now, what i'm finding is triangle count for each mesh inside glTF.
Use case is, I should provide a sorted mesh list by their face count, so our TA could find out those meshes which has unnecessary detail.

**Comment by fire** [comment]
So like your current mesh listed ui but sorted by face (gltf only supports triangles) count?

**Comment by fire** [comment]
I am also a huge fan of treemaps https://github.com/godotengine/godot-proposals/issues/80

**Comment by AllenDang** [comment]
@fire Yes, current mesh list with face count, and should with a ratio face_count / aabb.size to find those meshes have small size with huge detail.
Treemap will be great! I think I should implement one.

And another thing is, do you have any idea how to visualize UV from uv data? I'd like to show UV map visually to check whether it has overlap.

**Comment by fire** [comment]
Godot has one?

![image](https://user-images.githubusercontent.com/32321/203695735-a76ee19e-71d6-4c7e-9438-7708b9b14383.png)
![image](https://user-images.githubusercontent.com/32321/203695767-3f30c646-c032-4076-ac19-3d6b45937d24.png)

**Comment by AllenDang** [comment]
@fire Woo! That is convenient.

**Comment by AllenDang** [comment]
@fire I found the source code of godot to draw the uv, after line-by-line implementtion in gdscript, the performance is extremely slow....

**Comment by AllenDang** [comment]
@fire https://github.com/AllenDang/model_explorer_godot4/blob/main/script/DrawUVTex.gd
That's the implementation, double click mesh in left panel will trigger it.

**Comment by fire** [comment]
I'd probably force expose the c++ implementation and get a image.

**Comment by AllenDang** [comment]
@fire The function has other dependencies to the rest part and is editor only. I guess I have to implement that with GDExtension via C++ or Rust to improve performance.

**Comment by AllenDang** [comment]
@fire Sad news... I wrote a GDEtension via C++ to get the face_count, but performance is same with GDScript...

**Comment by fire** [comment]
I will try mesh mesh data tool.

**Comment by AllenDang** [comment]
@fire `mesh.mesh.surface_get_arrays(si)` is the key to impact performance, no matter via gdscript or c++.
Seems it will construct a temp array and copy the data inside.
I thought it may return a pointer to the array in memory, so c++ might be faster.

**Comment by fire** [comment]
Try

```gdscript
extends Node

class_name DrawUVTex

func draw_uv_texture(mesh: Mesh) -> PackedVector2Array:
	var uvLines: PackedVector2Array
	
	for si in mesh.get_surface_count():
		var mesh_data_tool : MeshDataTool = MeshDataTool.new()
		mesh_data_tool.create_from_surface(mesh, si)
		for edge_i in mesh_data_tool.get_edge_count():
			for vertex_i in range(2):
				var vertex = mesh_data_tool.get_edge_vertex(edge_i, vertex_i)
				var uv = mesh_data_tool.get_vertex_uv(vertex)
				uvLines.push_back(uv)
		
	return uvLines
```

**Comment by AllenDang** [comment]
@fire Same performance, take seconds to get face_count, and take tens of seconds to get uv points.

**Comment by fire** [comment]
Are you sure?

**Comment by fire** [comment]
https://user-images.githubusercontent.com/32321/203954509-2da8cd0b-db5c-4629-baa6-6f70b44c4ad2.mp4

[Mixer.zip](https://github.com/AllenDang/model_explorer_godot4/files/10090926/Mixer.zip) https://github.com/KhronosGroup/3DC-Certification/blob/main/models/Mixer/glTF-Binary/Mixer.glb

**Comment by fire** [comment]
I don't get a face count?

**Comment by AllenDang** [comment]
@fire I see, draw the UV is massive improved. Face count still slow.

**Comment by fire** [comment]
```gdscript
func face_count(mesh: Mesh) -> int:
	var face_count : int = 0
	for si in mesh.get_surface_count():
		var mesh_data_tool : MeshDataTool = MeshDataTool.new()
		mesh_data_tool.create_from_surface(mesh, si)
		face_count = face_count + mesh_data_tool.get_face_count()
	return face_count
```

**Comment by AllenDang** [comment]
@fire Still take seconds.

https://user-images.githubusercontent.com/18550/203960618-ac72b94f-c46c-4768-a943-28cf8755d191.mp4

**Comment by fire** [comment]
Try dev_build=off

**Comment by fire** [comment]
Check the size of the array and if the index exists and is trimesh divide by 3.

**Comment by AllenDang** [comment]
@fire Where to set dev_build=off? And I don't quite understand your suggestion `Check the size of the array and if the index exists and is trimesh divide by 3`...

**Comment by fire** [comment]
Check if this is slow. We create the ImporterMesh when importing. So the ideal case is we count there.

![image](https://user-images.githubusercontent.com/32321/204022215-8e7108a5-dcdc-4d40-8bce-93497bdf5248.png)

```gdscript
@tool
extends GLTFDocumentExtension

func _import_post(state, root):
	var nodes : Array[GLTFNode] = state.get_nodes()
	for node in nodes:
		if node.mesh != -1:
			var meshes : Array[GLTFMesh] = state.get_meshes()
			var mesh : GLTFMesh = meshes[node.mesh]
			var importer_mesh : ImporterMesh = mesh.mesh
			var array_mesh : ArrayMesh = importer_mesh.get_mesh()
			var faces : int = array_mesh.get_faces().size()
			print("%s %s" % [node.resource_name, faces])
```

https://github.com/V-Sekai/godot-gltf-sandbox/blob/main/addons/gltf_extensions/gltf_extensions.gd

**Comment by fire** [comment]
https://docs.godotengine.org/en/latest/development/compiling/index.html dev_build is a compile option.

**Comment by fire** [comment]
Note comment in docs:

>  to store data, use the set_additional_data and get_additional_data methods in GLTFState or GLTFNode.

![image](https://user-images.githubusercontent.com/32321/204023378-5d205988-a449-4f42-bc33-5e0f9172ae28.png)

**Comment by AllenDang** [comment]
@fire Using extension is not actually increase the performance, just move the lag into the post loading phase.
I did a perf test, same model.
 - without extension, loading time is 0.4 sec
 - with extension, loading time is 4.6 sec

**Comment by fire** [comment]
I don’t have any good ideas other than using the per rid info pr then.

**Comment by AllenDang** [comment]
@fire Still thank you from bottom of my heart!

**Comment by AllenDang** [comment]
@fire I got it! GLTFState has a property `json` contains information for all the meshes, read the indices there is lighting fast!

```gdscript
	var err = gltf_doc.append_from_file(file, gltf_state)
	
	var faceCountDic:Dictionary
	
	var nodes = gltf_state.json["nodes"]
	var meshes = gltf_state.json["meshes"]
	var accessors = gltf_state.json["accessors"]
	
	var i = 1
	for node in nodes:
		var name = "Empty#%d" % i
		if node.has("name"):
			name = node["name"].replace(".", "")
		i += 1
		
		if not node.has("mesh"):
			continue
			
		var mesh = meshes[node["mesh"]]
		
		var indicesCount = 0
		for primitive in mesh["primitives"]:
			var indices = primitive["indices"]
			var a = accessors[indices]
			indicesCount += a["count"]
			
		faceCountDic[name] = indicesCount / 3
```
